### ISSUE TITLE
Migration to 0.18

### ISSUE THREAD

**Issue by insdami** [torgeir/elm-github-events#1]
Hi there,

Would you be interested in migrating this project to 0.18.0? 
I can create a PR with the migration :)

**Comment by torgeir** [comment]
Yes! I never got it published because of some wierd issues in 17 that no one could explain, and I never got it to 18 because of the http dependency not being compatible yet. So yes, go for it! 😀

**Comment by torgeir** [comment]
Fixed in #2, released as [2.0.0](http://package.elm-lang.org/packages/torgeir/elm-github-events/2.0.0)
